dist: trusty

language: node_js

node_js:
  - '12'

cache: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn --frozen-lockfile

script:
  - yarn test
  - yarn build

after_script:
  - kill $SERVICE_PID

deploy:
  - provider: script
    script: yarn semantic-release --repository-url https://github.com/pchiwan/markdown-truncate.git
    on:
      branch: master
